import CoreGraphics
import CoreImage
import CoreImage.CIFilterBuiltins
import Foundation
import ImageIO
import UniformTypeIdentifiers

/// A QR code produced by the engine, in two reusable forms: a boolean module
/// matrix (row 0 = top, `true` = dark module, no quiet zone) for a host that
/// wants to draw its own symbol, and crisp PNG bytes with a baked-in quiet zone
/// for a host that just wants an image. Kept in `ProxyCore` (not the
/// Foundation-only `SharedModels`) because generation leans on CoreImage.
///
/// The underlying symbol is generated by CoreImage's `CIQRCodeGenerator`; this
/// type owns re-rendering it so the matrix and PNG are consistent and the PNG is
/// nearest-neighbour sharp at any module size, rather than exposing a blurry
/// scaled `CIImage`.
public struct QRCode: Sendable, Equatable {
    /// Module grid, row 0 = top row of the symbol, `true` = dark. Excludes the
    /// quiet zone (the white margin) — that is a rendering concern.
    public let matrix: [[Bool]]
    /// Side length of `matrix` in modules.
    public let moduleCount: Int
    /// PNG bytes: the matrix rendered at `modulePixels` per module with a
    /// `quietZoneModules`-wide white border. Empty only if PNG encoding failed.
    public let pngData: Data

    /// Error-correction level. Higher tolerates more damage at the cost of density.
    public enum Correction: String, Sendable {
        case low = "L", medium = "M", quartile = "Q", high = "H"
    }

    /// Generate a QR code for `string` (UTF-8). Returns `nil` if the string can't
    /// be encoded or CoreImage produces no symbol.
    ///
    /// - Parameters:
    ///   - modulePixels: pixels per module in `pngData` (bigger = larger image).
    ///   - quietZoneModules: width of the white border in `pngData`, in modules.
    ///     The QR spec recommends ≥ 4 for reliable scanning.
    ///   - correction: error-correction level.
    public static func generate(
        from string: String,
        modulePixels: Int = 12,
        quietZoneModules: Int = 4,
        correction: Correction = .medium
    ) -> QRCode? {
        guard let payload = string.data(using: .utf8) else { return nil }

        let filter = CIFilter.qrCodeGenerator()
        filter.message = payload
        filter.correctionLevel = correction.rawValue
        guard let output = filter.outputImage else { return nil }

        // Read the symbol at native resolution (1 module == 1 pixel) into a
        // grayscale buffer we fully control, so the matrix orientation and
        // thresholding don't depend on CoreImage's output pixel format.
        let extent = output.extent
        let width = Int(extent.width.rounded())
        let height = Int(extent.height.rounded())
        guard width > 0, height > 0 else { return nil }

        let context = CIContext(options: [.useSoftwareRenderer: true])
        guard let cg = context.createCGImage(output, from: extent) else { return nil }

        var gray = [UInt8](repeating: 0, count: width * height)
        guard let bitmap = CGContext(
            data: &gray,
            width: width,
            height: height,
            bitsPerComponent: 8,
            bytesPerRow: width,
            space: CGColorSpaceCreateDeviceGray(),
            bitmapInfo: CGImageAlphaInfo.none.rawValue
        ) else { return nil }
        bitmap.interpolationQuality = .none
        bitmap.draw(cg, in: CGRect(x: 0, y: 0, width: width, height: height))

        // `CGContext` is bottom-left origin, so buffer row 0 is the bottom of the
        // symbol — flip it so `matrix[0]` is the visual top row.
        var full = [[Bool]]()
        full.reserveCapacity(height)
        for y in 0 ..< height {
            let src = (height - 1 - y) * width
            var row = [Bool]()
            row.reserveCapacity(width)
            for x in 0 ..< width { row.append(gray[src + x] < 128) }
            full.append(row)
        }

        guard let trimmed = trimQuietZone(full) else { return nil }
        let png = renderPNG(matrix: trimmed, modulePixels: max(1, modulePixels), quietZone: max(0, quietZoneModules))
        return QRCode(matrix: trimmed, moduleCount: trimmed.count, pngData: png ?? Data())
    }

    /// Crop any all-white border CoreImage may have added, leaving just the data
    /// modules. Returns `nil` if the grid is entirely white.
    private static func trimQuietZone(_ grid: [[Bool]]) -> [[Bool]]? {
        var top = 0, bottom = grid.count - 1
        while top <= bottom, grid[top].allSatisfy({ !$0 }) { top += 1 }
        while bottom >= top, grid[bottom].allSatisfy({ !$0 }) { bottom -= 1 }
        guard top <= bottom else { return nil }

        let width = grid[0].count
        var left = 0, right = width - 1
        func columnEmpty(_ c: Int) -> Bool { (top ... bottom).allSatisfy { !grid[$0][c] } }
        while left <= right, columnEmpty(left) { left += 1 }
        while right >= left, columnEmpty(right) { right -= 1 }
        guard left <= right else { return nil }

        return (top ... bottom).map { Array(grid[$0][left ... right]) }
    }

    /// Draw `matrix` into an RGBA pixel buffer (row 0 = top) with a quiet zone and
    /// encode it as PNG. Manual buffer fill keeps orientation unambiguous.
    private static func renderPNG(matrix: [[Bool]], modulePixels: Int, quietZone: Int) -> Data? {
        let count = matrix.count
        guard count > 0 else { return nil }
        let dimModules = count + 2 * quietZone
        let side = dimModules * modulePixels
        var buffer = [UInt8](repeating: 255, count: side * side * 4) // opaque white

        for r in 0 ..< count {
            for c in 0 ..< matrix[r].count where matrix[r][c] {
                let x0 = (quietZone + c) * modulePixels
                let y0 = (quietZone + r) * modulePixels
                for y in y0 ..< y0 + modulePixels {
                    let rowBase = (y * side + x0) * 4
                    for x in 0 ..< modulePixels {
                        let idx = rowBase + x * 4
                        buffer[idx] = 0; buffer[idx + 1] = 0; buffer[idx + 2] = 0; buffer[idx + 3] = 255
                    }
                }
            }
        }

        guard let provider = CGDataProvider(data: Data(buffer) as CFData) else { return nil }
        guard let image = CGImage(
            width: side,
            height: side,
            bitsPerComponent: 8,
            bitsPerPixel: 32,
            bytesPerRow: side * 4,
            space: CGColorSpaceCreateDeviceRGB(),
            bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue),
            provider: provider,
            decode: nil,
            shouldInterpolate: false,
            intent: .defaultIntent
        ) else { return nil }

        let out = NSMutableData()
        guard let dest = CGImageDestinationCreateWithData(
            out as CFMutableData, UTType.png.identifier as CFString, 1, nil
        ) else { return nil }
        CGImageDestinationAddImage(dest, image, nil)
        guard CGImageDestinationFinalize(dest) else { return nil }
        return out as Data
    }
}
